name: dim_client
description: DIM demo.
version: 1.2.3
homepage: https://github.com/dimpart/demo-dart
repository: https://github.com/dimpart/demo-dart
issue_tracker: https://github.com/dimpart/demo-dart/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6

  object_key: ^1.1.1
  lnc: ^1.2.2
  pnf: ^1.3.3
#  startrek: ^1.2.0
  stargate: ^1.2.0

#  mkm: ^2.2.2
#  dkd: ^2.2.2
#  dimp: ^2.2.2
  dimsdk: ^2.2.1
  dim_plugins: ^2.2.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
